# Generated by Django 4.2.24 on 2025-09-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
